# Generated by Django 3.2.20 on 2025-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache', models.CharField(max_length=100)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
    ]
